feat: 80 perfect covered

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -72,6 +72,7 @@ jobs:
           poetry run pytest tests/ \
             --cov=src \
             --cov-report=xml \
+            --cov-report=html \
             --junitxml=pytest-report.xml
       
       - name: Upload coverage reports to Codecov
@@ -81,21 +82,21 @@ jobs:
             slug: victorgalantech/template-lambda
             fail_ci_if_error: true # Si Codecov falla, que falle el pipeline
       
-      # - name: Check coverage threshold
-      #   run: |
-      #     COVERAGE=$(poetry run coverage report --precision=2 | grep TOTAL | awk '{print $4}' | sed 's/%//')
-      #     echo "Current coverage: ${COVERAGE}%"
-      #     if (( $(echo "$COVERAGE < 80" | bc -l) )); then
-      #       echo "❌ Coverage is below 80% (current: ${COVERAGE}%)"
-      #       echo ""
-      #       echo "To check coverage locally, run:"
-      #       echo "  poetry run pytest tests/ --cov=src --cov-report=term-missing"
-      #       echo ""
-      #       echo "Make sure to add tests for uncovered code!"
-      #       exit 1
-      #     else
-      #       echo "✅ Coverage is ${COVERAGE}% (meets 80% requirement)"
-      #     fi
+      - name: Check coverage threshold
+        run: |
+          COVERAGE=$(poetry run coverage report --precision=2 | grep TOTAL | awk '{print $4}' | sed 's/%//')
+          echo "Current coverage: ${COVERAGE}%"
+          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
+            echo "❌ Coverage is below 80% (current: ${COVERAGE}%)"
+            echo ""
+            echo "To check coverage locally, run:"
+            echo "  poetry run pytest tests/ --cov=src --cov-report=term-missing"
+            echo ""
+            echo "Make sure to add tests for uncovered code!"
+            exit 1
+          else
+            echo "✅ Coverage is ${COVERAGE}% (meets 80% requirement)"
+          fi
 
 
   # Job 2: Build and Push Docker Image to ECR
@@ -103,7 +104,7 @@ jobs:
     name: Build & Push Docker Image
     runs-on: ubuntu-latest
     needs: quality-and-test
-    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
+    #if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
     
     outputs:
       image-tag: ${{ steps.meta.outputs.tags }}
